### ISSUE TITLE
Release note

### ISSUE THREAD

**Issue by Fr-Dae** [creimers/heic-to-jpg#10]
Make release evry big patch.
like all modification or issue fix
and that make you a clean and automatic release note

**Comment by creimers** [comment]
@Fr-Dae Please clarify, it is not quite clear what you're intending to communicate with this issue. Thanks!

**Comment by Fr-Dae** [comment]
https://github.com/Unitystation-fork/Unitystation-WikiV2/releases

release note automated genered and published.
easy to follow what change

**Comment by Fr-Dae** [comment]
here is what github recommends to use the full potential of it and facilitate monitoring.

create issues for each need or problem.
create a branch from this issue (bottom right)
make a PR to main with a PR comment.
when the PR is merged, the issue is closed.
and when you make a release, you can automatically make a release update, as shown in the example that you apparently didn't look at.

the release update shows all the merge PRs and the linked issues.

this makes it easier to track and review code, and makes your work more reliable and professional.
