### ISSUE TITLE
-v --version

### ISSUE THREAD

**Issue by Fr-Dae** [creimers/heic-to-jpg#11]
need it =)

**Comment by creimers** [comment]
@Fr-Dae Pull requests are welcome!

**Comment by Fr-Dae** [comment]
really?
You seriously want me to stick my nose into your code, without documentation, without knowing how it works, without any comments in the code.
to add a basic function such as displaying the version, which is nevertheless requested in the form issues

**Comment by creimers** [comment]
I'm closing the issue because of your rude response.
