### ISSUE TITLE
[LINUX] no heic here

### ISSUE THREAD

**Issue by Fr-Dae** [creimers/heic-to-jpg#13]
* heic-to-jpg version:0.1.9
* Python version: Python 3.10.12
* Operating System: 

- Ubuntu 22.04.3 LTS
- LXDE
- Linux version 5.15.0-83-generic (buildd@lcy02-amd64-027) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023
- 
```bash
free -h
               total       utilisé      libre     partagé tamp/cache   disponible
Mem:            15Gi       6,7Gi       1,4Gi       918Mi       7,0Gi       7,1Gi
Échange:      4,0Gi       496Mi       3,5Gi
```

### Description
```bash
heic-to-jpg -s ./ && cd ../
convert-im6.q16: unable to open image `*.[hH][eE][iI][cC]*': Aucun fichier ou dossier de ce type @ error/blob.c/OpenBlob/2924.
convert-im6.q16: no decode delegate for this image format `' @ error/constitute.c/ReadImage/575.
convert-im6.q16: no images defined `%[filename:base].jpg' @ error/convert.c/ConvertImageCommand/3229.
```

if the folder has no heic, simply display "no heic here" in GREEN
and automatically make a CD ../

**Comment by creimers** [comment]
@Fr-Dae Please clarify, it is not quite clear what you're intending to communicate with this issue. Please try to use the English language, I don't speak French. Thanks!

**Comment by Fr-Dae** [comment]
Why can't you go to deepl yourself and translate?
I don't speak any more English than you do French, so in the end it comes down to the same thing, one of us has to go to a translation site like deepl,

**Comment by creimers** [comment]
I'm closing the issue because of your rude response. It is you who is approaching me about this particular piece of software, not the other way around. I'm therefore expecting your to communicate in a clear, understandable and respectful way.
