### ISSUE TITLE
ImageMagick "convert" Deprecation Warning

### ISSUE THREAD

**Issue by rjhilgefort** [creimers/heic-to-jpg#14]
* heic-to-jpg version: latest? the tool doesn't appear to have a `--version` flag
* Python version: 3.13.0
* Operating System: Mac

### Description

Using the CLI tool with this version of ImageMagick shows deprecation warning. Just trying to not have this heic-to-jpg break on me with the next ImageMagick upgrade.

Version: `ImageMagick 7.1.1-40`
Deprecation warning: 
> WARNING: The convert command is deprecated in IMv7, use "magick" instead of "convert" or "magick convert"

### What I Did

Any command. Anything that calls with `convert` yields the warning. I _think_ we just need to update here
https://github.com/creimers/heic-to-jpg/blob/0c188f545a5f599e6d5cf4ae06c59f7825a6d8e8/heic_to_jpg/cli.py#L59

**Comment by creimers** [comment]
Thanks for the heads up, I will look into it asap.

**Comment by creimers** [comment]
@creimers I just released [version 0.2.0](https://github.com/creimers/heic-to-jpg/releases/tag/v0.2.0) to address this warning.

**Comment by creimers** [comment]
@rjhilgefort I just released [version 0.2.0](https://github.com/creimers/heic-to-jpg/releases/tag/v0.2.0) to address this warning.

**Comment by rjhilgefort** [comment]
Awesome, thank you!
