### ISSUE TITLE
Program 'convert' not found!

### ISSUE THREAD

**Issue by ml242** [creimers/heic-to-jpg#3]
* heic-to-jpg version:
* Python version:
* Operating System:

### Description

trying to convert a photo:

```Program 'convert' not found!```

### What I Did

Following the instructions, i added a photo to the path and ran ```heic-to-jpg -s ./IMG_240.heic --keep```

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by creimers** [comment]
Like stated in the [README.md](https://github.com/creimers/heic-to-jpg/blob/main/README.md), this program is just a wrapper around imagemagick's [convert](https://imagemagick.org/script/convert.php) cli. So you'll have to install it first (or imagemagick in general) in order for this to work. Here's a link: https://imagemagick.org/script/download.php

**Comment by ml242** [comment]
I see, I thought it came with it. You may want to add a link to the readme then.

**Comment by creimers** [comment]
Right you are. I updated the README just now.
