### ISSUE TITLE
What i do to convert heic-to-jpg, is the following

### ISSUE THREAD

**Issue by michaeldengxyz** [creimers/heic-to-jpg#4]
* heic-to-jpg version: N/A
* Python version: 3.8
* Operating System: Win10

### Description

What i do to convert heic-to-jpg, is the following:

### What I Did
import wand
from wand.image import Image as WImage
import traceback
import re

def WandHeic():
    fpath = 'H:/IMG_4804.HEIC'  

    try:
        with WImage(filename=fpath) as img:
            print(img.width, img.height)
            im = img.convert('jpeg')
            im.save(filename=fpath + '.JPG')
        
    except:
        print(traceback.format_exc())

**Comment by landa125** [comment]
Where did you add these lines of code?
`mport wand
from wand.image import Image as WImage
import traceback
import re

def WandHeic():
fpath = 'H:/IMG_4804.HEIC'

try:
    with WImage(filename=fpath) as img:
        print(img.width, img.height)
        im = img.convert('jpeg')
        im.save(filename=fpath + '.JPG')
    
except:
    print(traceback.format_exc()) `

**Comment by creimers** [comment]
I'm closing the issue as irrelevant.
