### ISSUE TITLE
Mention imagemagick dependency on Pypi

### ISSUE THREAD

**Issue by kevinlinxc** [creimers/heic-to-jpg#5]
People who google "heic to jpg python" will find the Pypi that is connected to this repo. This repo mentions installing imagemagick as a dependency, but the pypi page doesn't mention it and probably should.

**Comment by creimers** [comment]
It does say

> Essentially, this is just a wrapper around imagemagick's [convert](https://imagemagick.org/script/convert.php) cli.

I can make it even more explicit though.

**Comment by kevinlinxc** [comment]
I think you should, not everyone knows what imagemagick is.

**Comment by creimers** [comment]
I think this should be sufficiently clear now.

<img width="1129" alt="image" src="https://github.com/creimers/heic-to-jpg/assets/6090492/ce2b8872-b93a-4de7-adfe-10ce4d3c27cd">
