### ISSUE TITLE
Program 'convert' not found!

### ISSUE THREAD

**Issue by ahmed9779** [creimers/heic-to-jpg#6]
So I am running this command: 

heic-to-jpg --src "C:\Users\PC\Downloads\IMG.heic" --keep

and it says program convert not found.

I found later that installing ImageMagick might work however, that hasn't done anything.

I'm pretty new to this stuff so bare with me lol

**Comment by KurtLehnardt** [comment]
I'm seeing the same thing. Any updates?

**Comment by excusezmoi** [comment]
Having the same problem

**Comment by creimers** [comment]
What's the operating system you're using?

**Comment by excusezmoi** [comment]
Windows 10

**Comment by creimers** [comment]
@excusezmoi The Windows platform is not supported for now. Pull requests welcome!
