### ISSUE TITLE
Update installation doc

### ISSUE THREAD

**Issue by dasmalini** [creimers/heic-to-jpg#8]
* heic-to-jpg version: latest.
* Python version: Python 3.9.5
* Operating System: OS X 12.6.3

### Description

Describe what you were trying to get done:

`pip install heic-to-jpg`
Tell us what happened, what went wrong, and what you expected to happen:
it does as it's told, which is great, but for folks unfamiliar with python, they may be running python 2.x, and this fails if it's using python 2.x

My OSX system was running python2 out of the box IIRC.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

I did `pip3 install heic-to-jpg` and it works as expected after that. But I know python tooling, so it's unsurprising to me to do this. May not be as straightforward for others. 

### Recommendation

I'd recommend adding `pip3  install heic-to-jpg` as an alternative if the existing cli cmd fails. 

Additionally, you can list that python3 is a requirement on the splash page.

### Extras

Thank you so much for publishing this, you've saved me a mild headache having to write this tool myself. I hate airdropping, thinking I'm making this easier on myself, only to realize the file is a HEIC ...

**Comment by creimers** [comment]
@dasmalini Thanks for the feedback. I did update the install instructions.
